server:
  port: 1767



spring:  application:    name: api-gateway
  cloud:    gateway:      routes:      - id: dbservice
        uri: lb://dbservice
        predicates:        - Path=/users/**
 #       filters: #       - name: CircuitBreaker
 #         args: #           name: dbservice
 #           fallbackuri: forward:/dbFallback
      - id: bundle-service
        uri: lb://bundle-service
        predicates:        - Path=/bundles/**#        filters:#        - name: CircuitBreaker
#          args:
#              name: bundle-service 
#              fallbackuri: forward:/clientFallback  
