server:
  port: 8085
  
spring:  application:    name: cloud-config-server
  cloud:    config:      server:        git:          uri: https://github.com/wre1st/taleem-config-client
          